<?php
namespace ClearChat\ClearChat;
use pocketmine\plugin\PluginBase;
use pocketmine\event\Listener;
use pocketmine\command\Command;
use pocketmine\command\CommandSender;
use pocketmine\Player;
use pocketmine\Server;
use pocketmine\event\player\PlayerItemHeldEvent;
use pocketmine\event\entity\EntityDamageEvent;
use pocketmine\event\block\SignChangeEvent;
use pocketmine\event\entity\EntityDamageByEntityEvent;
use pocketmine\level\particle\FlameParticle;
use pocketmine\level\sound\LaunchSound;
use pocketmine\math\Vector3;
use pocketmine\utils\TextFormat as Color;
use pocketmine\item\Item;
use pocketmine\event\player\PlayerMoveEvent;
class Main extends PluginBase implements Listener{
	
		public function onEnable(){
			$this->getServer()->getPluginManager()->registerEvents($this, $this);
	}
	
	public function onCommand(CommandSender $sender, Command $command, string $label, array $args) : bool{
	    if(strtolower($command->getName()) == "cc"){
	                  if ($sender instanceof Player) {
		    	      if($sender->hasPermission("clearchat.clear")){
			$senderName = $sender->getName();
			$this->getServer()->broadcastMessage("§aChatul este șters");
			$this->getServer()->broadcastMessage("§aacest lucru poate duce la multe lucruri");
			$this->getServer()->broadcastMessage("§aPrecum:");
			$this->getServer()->broadcastMessage("§bReclamă");
			$this->getServer()->broadcastMessage("§bSpam");
			$this->getServer()->broadcastMessage("§bInjuraturi");
			$this->getServer()->broadcastMessage("§bSi Mai Multe.");
			$this->getServer()->broadcastMessage("§cChatul a fost șters de §b$senderName ..");
			$this->getServer()->broadcastMessage("§cVa rugam așteptați...");
			$this->getServer()->broadcastMessage("§cChatul este eliminat de §b$senderName ...");
			$this->getServer()->broadcastMessage("§cAcest lucru ar trebui să funcționeze destul de repede acum.");
			$this->getServer()->broadcastMessage("§dBun Venit pe Skyblock! :) Remediază doar chatul.");
			$this->getServer()->broadcastMessage("§dChat Eliminat. Adăugam mesaje.");
			$this->getServer()->broadcastMessage("§dClearChat plugin, updated by Rose. ;)");
			$this->getServer()->broadcastMessage("§dChatClear este un sistem minunat. :D");
			$this->getServer()->broadcastMessage("§eȘtiați, Minecraft a fost creat în 2009?");
			$this->getServer()->broadcastMessage("§eStiati,, §5Magic§bLounge§cPE §da fost server de java?");
			$this->getServer()->broadcastMessage("§eBine ați venit în sezonul 2! Construit de echipa noastră uimitoare de personal");
			$this->getServer()->broadcastMessage("§eChat Clear Acum se șterge.");
			$this->getServer()->broadcastMessage("§6Chatul se șterge.");
			$this->getServer()->broadcastMessage("§6Chatul se șterge.");
			$this->getServer()->broadcastMessage("§6Chatul se șterge.");
			$this->getServer()->broadcastMessage("§6Chatul se șterge.");
			$this->getServer()->broadcastMessage("§6Chatul se șterge.");
			$this->getServer()->broadcastMessage("§6Chatul se șterge.");
			$this->getServer()->broadcastMessage("§6Chatul se șterge.");
			$this->getServer()->broadcastMessage("§6Chatul se șterge.");
			$this->getServer()->broadcastMessage("§6Chatul se șterge.");
			$this->getServer()->broadcastMessage("§6Chatul se șterge.");
			$this->getServer()->broadcastMessage("§6Chatul se șterge.");
			$this->getServer()->broadcastMessage("§6Chatul se șterge.");
			$this->getServer()->broadcastMessage("§6Chatul se șterge.");
			$this->getServer()->broadcastMessage("§6Chatul se șterge.");
			$this->getServer()->broadcastMessage("§6Chatul se șterge.");
			$this->getServer()->broadcastMessage("§6Chatul se șterge.");
			$this->getServer()->broadcastMessage("§6Chatul se șterge.");
			$this->getServer()->broadcastMessage("§6Chatul se șterge.");
			$this->getServer()->broadcastMessage("§6Chatul se șterge.");
			$this->getServer()->broadcastMessage("§6Chatul se șterge.");
			$this->getServer()->broadcastMessage("§6Chatul se șterge.");
			$this->getServer()->broadcastMessage("§6Chatul se șterge.");
			$this->getServer()->broadcastMessage("§6Chatul se șterge.");
			$this->getServer()->broadcastMessage("§6Chatul se șterge.");
			$this->getServer()->broadcastMessage("§6Chatul se șterge.");
			$this->getServer()->broadcastMessage("§6Clearing Chat.");
			$this->getServer()->broadcastMessage("§6Clearing Chat.");
			$this->getServer()->broadcastMessage("§6Clearing Chat.");
			$this->getServer()->broadcastMessage("§6Clearing Chat.");
			$this->getServer()->broadcastMessage("§6Clearing Chat.");
			$this->getServer()->broadcastMessage("§6Clearing Chat.");
			$this->getServer()->broadcastMessage("§6Clearing Chat.");
			$this->getServer()->broadcastMessage("§6Clearing Chat.");
			$this->getServer()->broadcastMessage("§6Clearing Chat.");
			$this->getServer()->broadcastMessage("§6Clearing Chat.");
			$this->getServer()->broadcastMessage("§6Clearing Chat.");
			$this->getServer()->broadcastMessage("§6Clearing Chat.");
			$this->getServer()->broadcastMessage("§6Clearing Chat.");
			$this->getServer()->broadcastMessage("§6Clearing Chat.");
			$this->getServer()->broadcastMessage("§6Clearing Chat.");
			$this->getServer()->broadcastMessage("§6Clearing Chat.");
			$this->getServer()->broadcastMessage("§6Clearing Chat.");
			$this->getServer()->broadcastMessage("§6Clearing Chat.");
			$this->getServer()->broadcastMessage("§6Clearing Chat.");
			$this->getServer()->broadcastMessage("§6Clearing Chat.");
			$this->getServer()->broadcastMessage("§6Clearing Chat.");
			$this->getServer()->broadcastMessage("§6Clearing Chat.");
			$this->getServer()->broadcastMessage("§6Clearing Chat.");
			$this->getServer()->broadcastMessage("§6Clearing Chat.");
			$this->getServer()->broadcastMessage("§6Clearing Chat.");
			$this->getServer()->broadcastMessage("§6Clearing Chat.");
			$this->getServer()->broadcastMessage("§6Clearing Chat.");
			$this->getServer()->broadcastMessage("§6Clearing Chat.");
			$this->getServer()->broadcastMessage("§6Clearing Chat.");
			$this->getServer()->broadcastMessage("§6Clearing Chat.");
			$this->getServer()->broadcastMessage("§6Clearing Chat.");
			$this->getServer()->broadcastMessage("§6Clearing Chat.");
			$this->getServer()->broadcastMessage("§6Clearing Chat.");
			$this->getServer()->broadcastMessage("§6Clearing Chat.");
			$this->getServer()->broadcastMessage("§6Clearing Chat.");
			$this->getServer()->broadcastMessage("§6Clearing Chat.");
			$this->getServer()->broadcastMessage("§6Clearing Chat.");
			$this->getServer()->broadcastMessage("§6Clearing Chat.");
			$this->getServer()->broadcastMessage("§6Clearing Chat.");
			$this->getServer()->broadcastMessage("§6Clearing Chat.");
			$this->getServer()->broadcastMessage("§6Clearing Chat.");
			$this->getServer()->broadcastMessage("§6Clearing Chat.");
			$this->getServer()->broadcastMessage("§6Clearing Chat.");
			$this->getServer()->broadcastMessage("§6Clearing Chat.");
			$this->getServer()->broadcastMessage("§6Clearing Chat.");
			$this->getServer()->broadcastMessage("§6Clearing Chat.");
			$this->getServer()->broadcastMessage("§6Clearing Chat.");
			$this->getServer()->broadcastMessage("§6Clearing Chat.");
			$this->getServer()->broadcastMessage("§6Clearing Chat.");
			$this->getServer()->broadcastMessage("§6Clearing Chat.");
			$this->getServer()->broadcastMessage("§6Clearing Chat.");
			$this->getServer()->broadcastMessage("§6Clearing Chat.");
			$this->getServer()->broadcastMessage("§6Clearing Chat.");
			$this->getServer()->broadcastMessage("§6Clearing Chat.");
			$this->getServer()->broadcastMessage("§6Clearing Chat.");
			$this->getServer()->broadcastMessage("§6Clearing Chat.");
			$this->getServer()->broadcastMessage("§6Clearing Chat.");
			$this->getServer()->broadcastMessage("§6Clearing Chat.");
			$this->getServer()->broadcastMessage("§6Clearing Chat.");
			$this->getServer()->broadcastMessage("§6Clearing Chat.");
			$this->getServer()->broadcastMessage("§6Clearing Chat.");
			$this->getServer()->broadcastMessage("§6Clearing Chat.");
			$this->getServer()->broadcastMessage("§6Clearing Chat.");
			$this->getServer()->broadcastMessage("§6Clearing Chat.");
			$this->getServer()->broadcastMessage("§6Clearing Chat.");
			$this->getServer()->broadcastMessage("§6Clearing Chat.");
			$this->getServer()->broadcastMessage("§6Clearing Chat.");
			$this->getServer()->broadcastMessage("§6Clearing Chat.");
			$this->getServer()->broadcastMessage("§6Clearing Chat.");
			$this->getServer()->broadcastMessage("§6Clearing Chat.");
			$this->getServer()->broadcastMessage("§6Clearing Chat.");
			$this->getServer()->broadcastMessage("§6Clearing Chat.");
			$this->getServer()->broadcastMessage("§6Clearing Chat.");
			$this->getServer()->broadcastMessage("§6Clearing Chat.");
			$this->getServer()->broadcastMessage("§6Clearing Chat.");
			$this->getServer()->broadcastMessage("§6Clearing Chat.");
			$this->getServer()->broadcastMessage("§6Clearing Chat.");
			$this->getServer()->broadcastMessage("§6Clearing Chat.");
			$this->getServer()->broadcastMessage("§6Clearing Chat.");
			$this->getServer()->broadcastMessage("§6Clearing Chat.");
			$this->getServer()->broadcastMessage("§6Clearing Chat.");
			$this->getServer()->broadcastMessage("§6Clearing Chat.");
			$this->getServer()->broadcastMessage("§6Clearing Chat.");
			$this->getServer()->broadcastMessage("§6Clearing Chat.");
			$this->getServer()->broadcastMessage("§6Clearing Chat.");
			$this->getServer()->broadcastMessage("§6Clearing Chat.");
			$this->getServer()->broadcastMessage("§6Clearing Chat.");
			$this->getServer()->broadcastMessage("§6Clearing Chat.");
			$this->getServer()->broadcastMessage("§6Clearing Chat.");
			$this->getServer()->broadcastMessage("§6Clearing Chat.");
			$this->getServer()->broadcastMessage("§6Clearing Chat.");
			$this->getServer()->broadcastMessage("§6Clearing Chat.");
			$this->getServer()->broadcastMessage("§6Clearing Chat.");
			$this->getServer()->broadcastMessage("§6Clearing Chat.");
			$this->getServer()->broadcastMessage("§aChatul a fost șters de §b$senderName");
			return true;
		}
	}
	return true;
	}
}
